### ISSUE TITLE
TransformFeedback still has problems

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#53]
In chrome canary, sometimes it fails to draw the rect out. No error message is produced. I am now trying to find out the problems by reading OpenGL ES 3.0

**Comment by shrekshao** [comment]
Running WebGL 2 conformance test on canary can generate quite a lot failures related to transformfeedback. I decide to put off this fix....

```
failed: transform_feedback.point_size.triangles_separate: Result comparison failed
failed: transform_feedback.point_size.triangles_interleaved: Result comparison failed
```

**Comment by kenrussell** [comment]
Thanks for pointing out these failures. I'm embarrassed that I didn't notice them myself. They were due to bugs in the test and have been fixed in https://github.com/KhronosGroup/WebGL/pull/1422 . Some of the tests still fail; at least some, if not all, of these failures are due to bugs in the underlying graphics drivers. I'll analyze them. If you have questions about specific failing tests please ask me.

**Comment by shrekshao** [comment]
Revisit:
- Our samples seem to get rid of the "draw half of the rect sometimes" bug and works fine
-  the conformance test still failed on several tests ( but much fewer, focus on lowp and mediump now)

So i think it is okay to close this for now

**Comment by kenrussell** [comment]
Thanks for verifying. I still have more work to do in http://crbug.com/526748 to skip tests that are hitting known driver bugs. Please star the issue to get updates. After they're done let's revisit this to see what else needs to be done, or suppressed.

**Comment by pjcozzi** [comment]
@kenrussell you want to re-open this, right?

**Comment by kenrussell** [comment]
@pjcozzi I don't think it's necessary to reopen this unless your transform feedback sample is running into problems.
